# See https://github.com/golangci/golangci-lint/blob/master/.golangci.yml for an updated example.

run:
  # Allowed values: readonly|vendor|mod
  modules-download-mode: vendor # Changed from readonly to vendor
  timeout: 5m

linters-settings:
  depguard:
    rules:
      tests:
        deny:
          - pkg: github.com/stretchr/testify/assert
            desc: "Use github.com/stretchr/testify/require instead of testify/assert"
          - pkg: github.com/onsi/gomega
            desc: "Although Ginkgo is used in kubebuilder, use testify instead. Ginkgo is bloated providing little value."
          - pkg: github.com/onsi/ginkgo/v2
            desc: "Although Ginkgo is used in kubebuilder, use testify instead. Ginkgo is bloated providing little value."
          - pkg: github.com/onsi/ginkgo
            desc: "Although Ginkgo is used in kubebuilder, use testify instead. Ginkgo is bloated providing little value."
  misspell:
    locale: US
    ignore-words:
      - "statuser"
  nakedret:
    # make an issue if func has more lines of code than this setting and it has naked returns; default is 30
    max-func-lines: 0 # completely disallow naked returns
  nolintlint:
    allow-unused: false # report any unused nolint directives
    require-explanation: false # don't require an explanation for nolint directives
    require-specific: false # don't require nolint directives to be specific about which linter is being skipped

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - errcheck
    - copyloopvar
    - goimports
    - goprintffuncname
    - gosimple
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - staticcheck
    - stylecheck # replacement for golint
    - unconvert
    - unused
    - whitespace