# permissions for end users to view hostedsnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hostedsnapshot-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cosmos-operator
    app.kubernetes.io/part-of: cosmos-operator
    app.kubernetes.io/managed-by: kustomize
  name: hostedsnapshot-viewer-role
rules:
- apiGroups:
  - cosmos.strange.love
  resources:
  - hostedsnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cosmos.strange.love
  resources:
  - hostedsnapshots/status
  verbs:
  - get
