# permissions for end users to edit hostedsnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hostedsnapshot-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cosmos-operator
    app.kubernetes.io/part-of: cosmos-operator
    app.kubernetes.io/managed-by: kustomize
  name: hostedsnapshot-editor-role
rules:
- apiGroups:
  - cosmos.strange.love
  resources:
  - hostedsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cosmos.strange.love
  resources:
  - hostedsnapshots/status
  verbs:
  - get
