# permissions for end users to view statefuljobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: statefuljob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cosmos-operator
    app.kubernetes.io/part-of: cosmos-operator
    app.kubernetes.io/managed-by: kustomize
  name: statefuljob-viewer-role
rules:
- apiGroups:
  - cosmos.strange.love
  resources:
  - statefuljobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cosmos.strange.love
  resources:
  - statefuljobs/status
  verbs:
  - get
