apiVersion: cosmos.strange.love/v1alpha1
kind: ScheduledVolumeSnapshot
metadata:
  name: scheduledvolumesnapshot-sample
spec:
  # Required
  # SourceRef must be a CosmosFullNode
  sourceRef:
    namespace: default
    name: cosmoshub
  schedule: "0 * * * *" # hourly
  volumeSnapshotClassName: cosmos-snapshot

  # Optional
  minAvailable: 2 # optional
